### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by sat0chika** [sat0chika/chat-space#8]
#IPアドレス
54.178.56.208

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※今後実装に関する質問がありましたら、メンターに確認をお願いします！

**Comment by sat0chika** [comment]
Finished
